### ISSUE TITLE
Small problem with the socket

### ISSUE THREAD

**Issue by JBisc** [DanalEstes/PythonDSF#1]
First of all: GREAT work! I currently have with pyhton 3.8 under windows to connect with my Duet3

if I call 
```
#
# Just a short example how to use PythonDSF
#
import pythondcs
testInstance = pythondcs.PythonDCS();
```

I get the following warning

> AttributeError: module 'socket' has no attribute 'AF_UNIX'

if  I  Change

`self.DCSsock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
`

to 
`self.DCSsock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
`
I get

> TypeError: connect(): AF_INET address must be tuple, not str

Do you have any usefull tipps for me?

**Comment by DanalEstes** [comment]
This code ONLY works on the Raspberry Pi where DuetSoftwareFramework is installed. 

The socket call you found and changed is an internal UNIX memory socket.  Do not be fooled by the word "socket", these have nothing to do with websockets. 

Changing the socket initialization from AF_UNIX to something network related will not work, and would be the least of the changes required to other parts of the code to make it work with Duet RepRap V3 websockets. 

I may at some point release some Python that interfaces with Duet V2 and Duet V3 based printers via the network.  No promises.

**Comment by JBisc** [comment]
Thanks for your help. Will immediately try it on the raspberry
